"""users-table

Revision ID: 2e9ba1ae399a
Revises: e6e3ff422d71
Create Date: 2019-12-16 16:39:34.965145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e9ba1ae399a'
down_revision = 'e6e3ff422d71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('private_rooms',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('private_rooms')
    # ### end Alembic commands ###
