"""users-table

Revision ID: e6e3ff422d71
Revises: 8f66f3199a80
Create Date: 2019-12-16 15:20:41.211038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6e3ff422d71'
down_revision = '8f66f3199a80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_model', sa.Column('userImage', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_model', 'userImage')
    # ### end Alembic commands ###
