"""users table

Revision ID: 8f66f3199a80
Revises: 7f02f39d3a7d
Create Date: 2019-12-14 01:08:39.920234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f66f3199a80'
down_revision = '7f02f39d3a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_model_timestamp'), 'message_model', ['timestamp'], unique=False)
    op.drop_index('ix_messages_timestamp', table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_timestamp', 'messages', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_message_model_timestamp'), table_name='message_model')
    op.drop_table('message_model')
    # ### end Alembic commands ###
