"""users table

Revision ID: cafd5eae1731
Revises: 
Create Date: 2019-12-13 10:27:33.314158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cafd5eae1731'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_model_email'), 'user_model', ['email'], unique=True)
    op.create_index(op.f('ix_user_model_username'), 'user_model', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_model_username'), table_name='user_model')
    op.drop_index(op.f('ix_user_model_email'), table_name='user_model')
    op.drop_table('user_model')
    # ### end Alembic commands ###
